# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- hosts: ubuntu
  gather_facts: no
  tasks:
  - name: Install python version 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: result
    changed_when: result.rc != 0
    become: true

- hosts: ubuntu
  roles:
  - role: ansible-betacloud.proxy

- hosts: centos
  roles:
  - role: ansible-betacloud.proxy
