# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Configure proxy parameters for apt
  template:
    src: proxy-apt.j2
    dest: /etc/apt/apt.conf.d/01proxy
    owner: root
    group: root
    mode: 0644
  become: true
