---
- name: Configure proxy parameters for apt
  template:
    src: proxy-apt.j2
    dest: "{{ proxy_apt_conf_path }}"
    owner: root
    group: root
    mode: 0644
  become: true
  when: proxy_proxies != {}
