# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"
  when: proxy_package_manager|bool

- name: Copy environment file for system wide settings
  template:
    src: environment.j2
    dest: /etc/environment
    owner: root
    group: root
    mode: 0644
  become: true
