---
- name: Include distribution specific tasks
  include: "{{ ansible_os_family }}.yml"
  when: proxy_package_manager|bool

- name: Set system wide settings in environment file
  blockinfile:
    dest: /etc/environment
    marker: "# {mark} ANSIBLE MANAGED BLOCK (osism.proxy)"
    block: |
      export http_proxy={{ proxy_proxies['http']  }}
      export HTTP_PROXY={{ proxy_proxies['http']  }}

      export https_proxy={{ proxy_proxies['https'] |default(proxy_proxies['http'] ) }}
      export HTTPS_PROXY={{ proxy_proxies['https'] |default(proxy_proxies['http'] ) }}

      export ftp_proxy={{ proxy_proxies['http']  }}
      export FTP_PROXY={{ proxy_proxies['http']  }}

      export rsync_proxy={{ proxy_proxies['http'] }}
      export RSYNC_PROXY={{ proxy_proxies['http']  }}

      export no_proxy={{ proxy_no_proxy|join(',') }}
  become: true
  when: proxy_proxies != {}
