Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"
    ubuntu.vm.hostname = "proxy-ubuntu"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
#      ansible.galaxy_role_file = '../test-requirements.yml'
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "proxy-centos"
    centos.vm.synced_folder ".", "/vagrant", disabled: true
    centos.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
#      ansible.galaxy_role_file = '../test-requirements.yml'
    end
  end
end
